apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBUGt54MvIKZYajSEQ1UHrG4bt40wAP4ApZsN9KosgmpDJXJ61PoIBRvH6y4zl50sGLQUGkP5tFl9syoPk/KmrOzhAF9U2v4oeh+Dy/U462QmyQUrnmA6HAqRPcZf1VDucqhZlGxA6gDXRX+kI0kbzEVM17dhOaimF3QlwoxGX9JsXypCGoADtSubC2P9BDQ7uQlAHQj3u5C+n2z78B+T5z+Gx59x5/jl5k74NbZKCBLXEYWaXy8VPjtKkWA0H/ODjyfCyb8bc1d3lRFgsWsa8SUaHAYthXnTlPNHFLDhDOqFaIlCb+p866F4hZQEOP75a8JB1JDZyCfRt+0eTkRN5KhO2Lwb8kpfNBidOhY3HDIFol+B0WsN7XaBYqG5bOgjOsFwwz793Af/RTGNPhGRJ/tzUpr08pFG7MZhaoJZciDobFX6k71tO8CAYlzf0CIhJaDNnsJS3oVN+KC0awHxkWhmrxj2EjBSywfLBbpJGpKQDHp7ro9dv50O4i7BW/9ggaNP6SvxvrBtIQ5DAoGDDJya5n2EvEzohy0EdyqTjwKF46fcacpgjJJ18bPAkaT+Q1M/vATQ3p8Z/EkIuNZjRxS2Tq55pLx6OzATA0HQIIf1+7/KRyjaWukcMrBseNLKWkgswJb6bHj6lU7l4nSc0rN1fZZEX0C59U6hvhtyk/eupRWqtm87lRCTBCPepnrZH+thbIfmn+2w==
    DB_USER: AgCTJPjJvNBwoihwCN7lOb4pyDvMQLvojlGmlS8ku6vAAAow8BXo8xX8kWaaOQE8UcN/S6WbKs/URdh3rKe4NqxZlBgvOy1XSmt2XPNaaqQovHk09jgPRIWcU11vqG6qB2eHD+5DZ9RXxcE9WQsCzQYdAgvKTA3ti9A2SA8CfOo0CK8b7ZoaCqWlH3sP951HA9Wmx5zbYoo3zjceRJuYr5hxjH8RQjdFf2btCYmBfhI/i5Xjs7b4Bk6mG+z01LC95bsJwshg9dTqYyqVlMm9gUIF4bbWhFCKFR6T1LBKNxsSM3JmRMccuSulbiZTYnOI9RxnC8FX3DYbNWhhUOXasTDXMCWfCrQfU+gwact8UyEk9rxbjXKLfjlfYhu2QVeth5b1QDbwg/tVsVioWAbjoZxVyH8+NDau2WAX8OBNcZePCvLvKkOPxjcCYst2yEoJIKnnGJWKUMz07W9ygOxHnDBsCujiVEfby8O+jLdOPBakq9wjWOZ/svwcodXnWF7MNutroHyhP52C7X47//FR6W02W/mnR2XbLd4B/YHTtcD/ZgW4LE0gEqjQkw6GsDfiTyOx2GJDy69XUvb7PdA3LANzGMDvC7LrYU+hRO2QjkjGiPdoniK9xSv68WDwOuLCVUSfK1RBVGiUwSrvdmIOuP3QDHXPi5TqmU5aYMzYVUYLP5sPMZ/MWGbmwXbg4f2rNR5778rYZr90Uw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

